version: '3'

services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "5000-5444:5000-5444"
    networks:
      - grid

  node-chrome:
    image: selenium/node-chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=5122
      - SE_EVENT_BUS_SUBSCRIBE_PORT=5233
    networks:
      - grid

  node-firefox:
    image: selenium/node-firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=5122
      - SE_EVENT_BUS_SUBSCRIBE_PORT=5233
    networks:
      - grid
      

networks:
  grid:
    driver: bridge
